import { useState } from 'react';
import { ArrowRight, Check, Info, Minus, Plus } from 'lucide-react';
import { Link } from 'react-router-dom';
import ServicePageLayout from '../components/ServicePageLayout';
import PlacementExplorer from '../components/PlacementExplorer';
import FAQ from '../components/FAQ';
import { useCart } from '../context/CartContext';
import { useLocale } from '../context/LocaleContext';
import { useSEO } from '../hooks/useSEO';
import { trackEvent, trackMetaEvent } from '../lib/analytics';

type GuestPackage = {
  id: string;
  name: string;
  count: string;
  title: string;
  items: string[];
  price: number;
  cta: string;
  popular?: boolean;
};

const packagesEn: GuestPackage[] = [
  { id: 'start', name: 'START', count: '3 GUEST POSTS', title: 'Three good reasons not to pick the first sites you find.', price: 510, cta: 'Find My Publications', items: ['3 publications worth considering. We research, you approve.', '3 original articles included. Written by human copywriters, not generated by AI.', 'A different idea for every site. Because the publication comes before the article.', 'We handle the publisher. Outreach, negotiation, edits and getting it live.', 'Your link has to belong there. Page, anchor and context matched together.', '1-Year Link Care'] },
  { id: 'grow', name: 'GROW', count: '5 GUEST POSTS', title: 'Five articles. Five different reasons to get published.', price: 825, cta: 'Build My Coverage', popular: true, items: ['Start with your competitors. Where are they getting published — and which opportunities are worth following?', 'Find what they missed. Publications and topics where your brand can show up instead.', '5 publications, researched around the campaign. Not five sites pulled from a database.', '5 original angles + 5 human-written articles. Each built for where it’s going.', 'Spread the links properly. Different pages, anchors and contexts where it makes sense.', 'We handle everything between “good idea” and “published.”', '1-Year Link Care', 'Campaign wrap-up. What worked, what we found and what we’d target next.'] },
  { id: 'scale', name: 'SCALE', count: '10 GUEST POSTS', title: 'Ten publications is where this stops being an order. And starts becoming a campaign.', price: 1600, cta: 'Build My Campaign', items: ['Map where your market gets published. Competitors, publications, topics and obvious gaps.', 'Build the publication mix. We don’t need ten versions of the same website.', 'Plan the campaign before writing article #1. Which pages need support, which topics make sense and where each belongs.', '10 original articles. 10 actual angles. Human-written — no AI article factory.', 'Go beyond competitor copying. Their placements are research, not our shopping list.', 'Use your best pages properly. Homepage, commercial pages and resources distributed according to context.', 'Publisher work is on us. Research, outreach, negotiation, content, revisions and publication.', '1-Year Link Care', 'Next Opportunity Map. The next publications and topics we’d go after based on what we learned.'] },
];

const packagesUk: GuestPackage[] = [
  { id: 'start', name: 'START', count: '3 ГОСТЬОВІ ПУБЛІКАЦІЇ', title: 'Три добрі причини не обирати перші сайти, що трапилися.', price: 510, cta: 'Знайти мої видання', items: ['3 видання, які варто розглянути. Ми досліджуємо, ви погоджуєте.', '3 оригінальні статті. Написані людьми, не згенеровані AI.', 'Окрема ідея для кожного сайту. Видання — перед статтею.', 'Ми працюємо з паблішером: аутріч, переговори, правки та публікація.', 'Ваше посилання має бути доречним. Сторінка, анкор і контекст підібрані разом.', 'Link Care на 1 рік'] },
  { id: 'grow', name: 'GROW', count: '5 ГОСТЬОВИХ ПУБЛІКАЦІЙ', title: 'П’ять статей. П’ять різних причин бути опублікованими.', price: 825, cta: 'Будувати охоплення', popular: true, items: ['Починаємо з конкурентів. Де вони публікуються і які можливості справді варті уваги?', 'Знаходимо те, що вони пропустили.', '5 видань, досліджених під кампанію. Не п’ять сайтів із бази.', '5 оригінальних кутів + 5 статей від людей.', 'Розподіляємо посилання правильно: різні сторінки, анкори та контексти.', 'Ми беремо на себе шлях від ідеї до публікації.', 'Link Care на 1 рік', 'Підсумок кампанії та наступні можливості.'] },
  { id: 'scale', name: 'SCALE', count: '10 ГОСТЬОВИХ ПУБЛІКАЦІЙ', title: 'Десять видань — це вже не замовлення. Це кампанія.', price: 1600, cta: 'Будувати кампанію', items: ['Мапа ринку: конкуренти, видання, теми та очевидні прогалини.', 'Будуємо мікс видань. Нам не потрібно десять версій одного сайту.', 'Плануємо кампанію до написання першої статті.', '10 оригінальних статей. 10 справжніх кутів. Без AI-фабрики.', 'Розміщення конкурентів — це дослідження, а не список покупок.', 'Правильно використовуємо найкращі сторінки.', 'Паблішерська робота на нас: дослідження, аутріч, переговори, контент і публікація.', 'Link Care на 1 рік', 'Мапа наступних можливостей на основі того, що ми дізналися.'] },
];

const qualityEn = [
  ['01', 'RELEVANCE', 'Does this publication actually make sense for your business?'],
  ['02', 'REAL TRAFFIC', 'We want websites people and search engines actually visit.'],
  ['03', 'THE AUDIENCE', 'Who is this article being written for — besides Google?'],
  ['04', 'THE OPPORTUNITY', 'Can we create something worth publishing here?'],
];

const qualityUk = [
  ['01', 'РЕЛЕВАНТНІСТЬ', 'Чи справді це видання має сенс для вашого бізнесу?'],
  ['02', 'РЕАЛЬНИЙ ТРАФІК', 'Нам потрібні сайти, які відвідують люди та пошуковики.'],
  ['03', 'АУДИТОРІЯ', 'Для кого пишеться ця стаття — крім Google?'],
  ['04', 'МОЖЛИВІСТЬ', 'Чи можемо ми створити тут матеріал, який варто опублікувати?'],
];

const stepsEn = [
  ['01', 'FIND SOMEWHERE WORTH PUBLISHING.', 'Not somewhere willing to take anything.'],
  ['02', 'GIVE THEM A REASON TO SAY YES.', 'The topic has to work for the publication too.'],
  ['03', 'WRITE FOR THEIR AUDIENCE.', 'Human-written. No AI article factory.', 'Their audience first. Your link second.'],
  ['04', 'GET IT OVER THE LINE.', 'Outreach, negotiation, edits and publication — handled.'],
];

const stepsUk = [
  ['01', 'ЗНАЙТИ МІСЦЕ, ДЕ ВАРТО ПУБЛІКУВАТИСЯ.', 'Не просто сайт, який готовий прийняти будь-що.'],
  ['02', 'ДАТИ ЇМ ПРИЧИНУ СКАЗАТИ «ТАК».', 'Тема має працювати і для самого видання.'],
  ['03', 'ПИСАТИ ДЛЯ ЇХНЬОЇ АУДИТОРІЇ.', 'Написано людьми. Без AI-фабрики.', 'Спочатку їхня аудиторія. Потім ваше посилання.'],
  ['04', 'ДОВЕСТИ СПРАВУ ДО ПУБЛІКАЦІЇ.', 'Аутріч, переговори, правки та публікація — на нас.'],
];

const faqEn = [
  { q: 'Is the article included?', a: 'Yes. Every placement includes an original article written by a human copywriter. We don’t use AI-generated articles for delivery.' },
  { q: 'Can I approve the websites before you publish?', a: 'Yes. We can send publications for approval before moving forward.' },
  { q: 'Can I approve the topics and articles too?', a: 'Yes. Tell us how involved you want to be before the campaign starts.' },
  { q: 'Can I choose the target URL and anchor?', a: 'Yes. We’ll work with your preferred pages and anchors, but we’ll tell you if something doesn’t fit naturally.' },
  { q: 'Do you only work with DR 50+ websites?', a: 'No. That’s kind of the point. We look at relevance, organic traffic, site quality, activity and other signals together rather than treating one metric as quality.' },
  { q: 'How long does the placement stay live?', a: 'Placements include 1-Year Link Care. We monitor delivered placements during the coverage period and review eligible removals according to the Link Care policy.' },
  { q: 'What’s the difference between Guest Posting and Link Insertions?', a: 'Guest Posting creates and publishes a new article. Link Insertions place your link into an article that’s already live.' },
];

const faqUk = [
  { q: 'Стаття включена?', a: 'Так. Кожне розміщення включає оригінальну статтю від людини-копірайтера. Ми не використовуємо AI-статті для доставки.' },
  { q: 'Чи можу я погодити сайти до публікації?', a: 'Так. Ми можемо надіслати видання на погодження до початку роботи.' },
  { q: 'Чи можу я погоджувати теми та статті?', a: 'Так. Скажіть, наскільки залученими ви хочете бути до старту кампанії.' },
  { q: 'Чи можу я обрати цільовий URL та анкор?', a: 'Так. Ми працюємо з вашими сторінками та анкорами, але скажемо, якщо щось не вписується природно.' },
  { q: 'Ви працюєте лише із сайтами DR 50+?', a: 'Ні. У цьому й сенс. Ми дивимося на релевантність, органічний трафік, якість та активність сайту разом.' },
  { q: 'Як довго живе розміщення?', a: 'Розміщення включають Link Care на 1 рік. Ми стежимо за ними та розглядаємо видалення за політикою Link Care.' },
  { q: 'Чим гостьові публікації відрізняються від розміщень у готових статтях?', a: 'Гостьовий постинг створює та публікує нову статтю. Розміщення посилань додають ваше посилання до вже опублікованої статті.' },
];

export default function GuestPostingPage() {
  const { locale, localizePath: lp } = useLocale();
  const uk = locale === 'uk';
  const packages = uk ? packagesUk : packagesEn;
  const quality = uk ? qualityUk : qualityEn;
  const steps = uk ? stepsUk : stepsEn;
  const faqs = (uk ? faqUk : faqEn).map((faq, index) => index === 6 ? {
    ...faq,
    a: uk ? <>Гостьовий постинг створює та публікує нову статтю. <a href={lp('/services/niche-edits')} className="font-bold underline underline-offset-2 hover:text-white">Розміщення посилань</a> додають ваше посилання до вже опублікованої статті.</> : <>Guest Posting creates and publishes a new article. <a href={lp('/services/niche-edits')} className="font-bold underline underline-offset-2 hover:text-white">Link Insertions</a> place your link into an article that’s already live.</>,
  } : faq);
  const { addItem, items } = useCart();
  const [quantities, setQuantities] = useState<Record<string, number>>({});
  const [careOpen, setCareOpen] = useState(false);

  useSEO({
    title: uk ? 'Гостьові публікації — Vladenza' : 'Guest Posting — Vladenza',
    description: uk ? 'Оригінальні статті на виданнях, де ваш бренд справді має бути.' : 'Original articles on publications where your brand actually belongs.',
    canonical: `https://vladenza.com${lp('/services/guest-posting')}`,
  });

  const getQuantity = (id: string) => quantities[id] ?? 1;
  const changeQuantity = (id: string, delta: number) => setQuantities((current) => ({ ...current, [id]: Math.max(1, (current[id] ?? 1) + delta) }));
  const addToCampaign = (pkg: GuestPackage) => {
    const quantity = getQuantity(pkg.id);
    const productId = `guest-post-${pkg.id}`;
    addItem({ productId, service: 'Guest Posting', name: `Guest Posting — ${pkg.name}`, description: pkg.count, unitPrice: pkg.price }, quantity);
    trackEvent('add_to_cart', { product_id: productId, quantity, price: pkg.price });
    trackMetaEvent('AddToCart', { content_name: `Guest Posting ${pkg.name}`, content_category: 'Guest Posting', content_ids: [productId], content_type: 'product', value: pkg.price * quantity, currency: 'USD', contents: [{ id: productId, quantity, item_price: pkg.price }] });
    setQuantities((current) => ({ ...current, [pkg.id]: 1 }));
  };

  return (
    <ServicePageLayout defaultService="Guest Posting" flushTop>
      <main>
        <section className="relative flex min-h-[540px] items-center overflow-hidden bg-navy text-white sm:min-h-[580px] lg:min-h-[620px]">
          <img src="/assets/visuals/Guest_post.png" alt="" className="absolute inset-0 h-full w-full object-cover object-[68%_center] sm:object-center" />
          <div className="absolute inset-0 bg-[#07102B]/75" />
          <div className="paper-grain absolute inset-0 opacity-20" />
          <div className="relative z-10 mx-auto flex w-full max-w-5xl flex-col items-center px-5 py-16 text-center sm:px-8 sm:py-20 lg:py-24">
            <p className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-signal">{uk ? 'ГОСТЬОВІ ПУБЛІКАЦІЇ' : 'GUEST POSTING'}</p>
            <h1 className="max-w-5xl font-display text-[clamp(2.75rem,7vw,6.75rem)] font-bold leading-[.95] tracking-[-.05em] text-cream">{uk ? <>Ваша стаття заслуговує на більше, ніж<br /><span className="text-signal">«будь-який сайт із DR 50+».</span></> : <>Your article deserves better than<br /><span className="text-signal">“any site with DR 50+.”</span></>}</h1>
            <div className="mt-8 flex w-full max-w-[360px] flex-col gap-3 sm:max-w-none sm:flex-row sm:justify-center"><a href="#packages" className="editorial-focus inline-flex min-h-14 items-center justify-center gap-2 bg-signal px-7 text-base font-bold text-white transition-colors hover:bg-[#EA580C]">{uk ? 'Обрати пакет' : 'Choose Your Package'} <ArrowRight size={18} /></a><a href="#placements" className="editorial-focus inline-flex min-h-14 items-center justify-center gap-2 bg-[#FFFDF8] px-7 text-base font-bold text-navy transition-colors hover:bg-white">{uk ? 'Переглянути розміщення' : 'See Placements'} <ArrowRight size={18} /></a></div>
          </div>
        </section>

        <section id="packages" className="scroll-mt-20 bg-cream py-14 md:py-20"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-16"><div className="mb-8 max-w-3xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-signal">01 / {uk ? 'Пакети гостьового постингу' : 'GUEST POSTING PACKAGES'}</p><h2 className="font-display text-[clamp(2.5rem,4vw,4.5rem)] font-bold leading-[.96]">{uk ? 'Наскільки далеко ви хочете це розвинути?' : 'Choose how far you want us to take it.'}</h2></div><div className="grid items-stretch gap-5 lg:grid-cols-3">{packages.map((pkg) => { const quantity = getQuantity(pkg.id); const productId = `guest-post-${pkg.id}`; const inCart = items.find((item) => item.productId === productId); return <article key={pkg.id} className={`relative flex h-full flex-col border-2 border-ink bg-white p-5 transition-transform hover:-translate-y-1 sm:p-6 ${pkg.popular ? 'shadow-[6px_6px_0_#FF5A1F]' : ''}`}>
          {pkg.popular && <span className="absolute right-5 top-0 -translate-y-1/2 bg-signal px-3 py-1 text-[10px] font-bold uppercase tracking-[.14em] text-white">{uk ? 'Найпопулярніший' : 'Most popular'}</span>}
          <p className="text-xs font-bold uppercase tracking-[.16em] text-signal">{pkg.name}</p><p className="mt-2 text-sm font-bold text-ink/55">{pkg.count}</p><h3 className="mt-6 max-w-sm font-display text-[25px] font-bold leading-[1.05]">{pkg.title}</h3>
          <ul className="mt-6 flex flex-col gap-3 border-t-2 border-ink/10 pt-5">{pkg.items.map((item) => <li key={item} className="flex gap-3 text-[15px] leading-6 text-ink/75"><Check size={16} className="mt-1 shrink-0 text-signal" />{item === '1-Year Link Care' || item === 'Link Care на 1 рік' ? <><span>{item}</span><button type="button" onClick={() => setCareOpen(true)} aria-label="Link Care details" className="editorial-focus inline-flex text-ink/55 hover:text-signal"><Info size={14} /></button></> : item}</li>)}</ul>
          <div className="mt-auto pt-6"><div className="flex items-center justify-between border-t-2 border-ink/10 pt-5"><span className="font-display text-3xl font-bold text-ink">${pkg.price}</span><div className="flex items-center border-2 border-ink"><button type="button" onClick={() => changeQuantity(pkg.id, -1)} className="editorial-focus flex h-9 w-9 items-center justify-center text-ink/60 hover:bg-ink/5" aria-label="Decrease quantity"><Minus size={15} /></button><span className="flex h-9 min-w-8 items-center justify-center border-x-2 border-ink text-sm font-bold">{quantity}</span><button type="button" onClick={() => changeQuantity(pkg.id, 1)} className="editorial-focus flex h-9 w-9 items-center justify-center text-ink/60 hover:bg-ink/5" aria-label="Increase quantity"><Plus size={15} /></button></div></div><p className="mt-1 text-right text-xs font-medium text-ink/45">{uk ? 'за пакет' : 'per package'}</p><button type="button" onClick={() => addToCampaign(pkg)} className={`editorial-focus mt-4 inline-flex min-h-12 w-full items-center justify-center gap-2 px-5 text-sm font-bold transition-colors ${pkg.popular ? 'bg-signal text-white hover:bg-[#EA580C]' : 'bg-navy text-white hover:bg-[#101F52]'}`}>{inCart ? (uk ? 'Додати ще' : 'Add More') : pkg.cta}<ArrowRight size={16} /></button></div>
        </article>; })}</div><p className="mt-8 border-t-2 border-ink pt-5 text-[16px] leading-7 text-ink/65">{uk ? 'Кожен пакет включає дослідження, роботу з паблішером, контент від людини, публікацію та звітність. Без AI-статей.' : 'Every package includes research, publisher outreach, human-written content, publication and reporting. No AI-generated articles.'}</p></div></section>

        <section className="bg-white py-14 md:py-20"><div className="mx-auto max-w-[1240px] px-5 sm:px-8 lg:px-16"><div className="max-w-3xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-signal">02 / {uk ? 'Де це доречно' : 'WHERE IT BELONGS'}</p><h2 className="font-display text-[clamp(2.5rem,4vw,4.5rem)] font-bold leading-[.96]">{uk ? <>Хороша метрика не робить<br />хороше видання.</> : <>A good metric doesn't make<br />a good publication.</>}</h2></div><div className="mt-10 grid border-y-2 border-ink md:grid-cols-2">{quality.map(([number, title, body], index) => <div key={number} className={`py-6 md:p-7 ${index % 2 === 0 ? 'md:border-r-2 md:border-ink' : ''} ${index < 2 ? 'border-b-2 border-ink' : ''}`}><p className="font-display text-4xl text-signal">{number}</p><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-ink/45">{title}</p><p className="mt-2 max-w-sm font-display text-[21px] font-bold leading-tight">{body}</p></div>)}</div><p className="mt-8 max-w-3xl text-[16px] leading-7 text-ink/65">{uk ? 'Метрики важливі. Ми дивимося на авторитет, органічний трафік, історію та якість сайту — просто не вдаємо, що одне число пояснює все.' : "Metrics still matter. We look at authority, organic traffic, history and site quality — we just don't pretend one number tells the whole story."}</p></div></section>

        <section className="bg-navy py-14 text-white md:py-20"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 sm:px-8 md:grid-cols-[.8fr_1.2fr] md:gap-16 lg:px-16"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.18em] text-signal">03 / {uk ? 'За що ви платите' : 'WHAT YOU’RE ACTUALLY PAYING FOR'}</p><h2 className="font-display text-[clamp(2.75rem,5vw,5rem)] font-bold leading-[.9] text-cream">{uk ? <>Написати статтю<br /><span className="text-signal">— лише половина роботи.</span></> : <>Writing the article<br /><span className="text-signal">is only half the job.</span></>}</h2><p className="mt-6 max-w-md text-[16px] leading-7 text-white/65">{uk ? 'Знайти видання, тему та правильне посилання — друга половина.' : 'Getting the publication, topic and link to work together is the other half.'}</p></div><div className="relative">{steps.map(([number, title, body, emphasis], index) => <div key={number} className="relative flex gap-5 border-b border-white/20 py-5 first:pt-0 last:border-0"><div className="relative z-10 flex h-9 w-9 shrink-0 items-center justify-center border border-signal bg-navy text-sm font-bold text-signal">{number}</div><div><h3 className="font-display text-xl text-cream sm:text-2xl">{title}</h3><p className="mt-1 text-[15px] leading-6 text-white/60">{body}</p>{emphasis && <p className="mt-2 font-display text-lg font-bold text-signal">{emphasis}</p>}</div>{index < 3 && <div className="absolute left-[18px] top-14 h-full w-px bg-signal/40" />}</div>)}</div><div className="border-t border-white/20 pt-5 md:col-span-2"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-signal">{uk ? 'ВАША КАМПАНІЯ, ВАШ ВИБІР' : 'YOUR CAMPAIGN, YOUR CALL'}</p><p className="mt-2 font-display text-2xl text-cream sm:text-3xl">{uk ? 'Погоджуйте видання. Погоджуйте теми. Або довірте нам усе.' : 'Approve the publications. Approve the topics. Or leave the whole thing to us.'}</p><p className="mt-1 text-[15px] text-white/50">{uk ? 'Без постійного контролю.' : 'No babysitting required.'}</p></div></div></section>

        <section id="placements" className="scroll-mt-20 bg-cream py-14 md:py-20"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-16"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-signal">04 / {uk ? 'Докази' : 'THE RECEIPTS'}</p><h2 className="font-display max-w-3xl text-[clamp(2.5rem,4vw,4.5rem)] font-bold leading-[.96]">{uk ? <>Менше розмов.<br />Більше публікацій, які ми справді зробили.</> : <>Less talk.<br />More links we've actually placed.</>}</h2><p className="mt-4 mb-8 max-w-xl text-[16px] leading-7 text-ink/65">{uk ? 'Реальні приклади гостьових публікацій із виконаних замовлень.' : 'Real guest posting examples from completed orders.'}</p><PlacementExplorer serviceType="guest_post" /><div className="mt-6"><Link to={lp('/placements')} className="inline-flex items-center gap-2 text-sm font-bold text-signal hover:text-[#EA580C]">{uk ? 'Усі розміщення' : 'See All Placements'} <ArrowRight size={15} /></Link></div></div></section>

        <section className="bg-[#D94712] py-14 text-[#FFFDF8] md:py-20"><div className="mx-auto max-w-5xl px-5 sm:px-8"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-white/75">05 / {uk ? 'Перед запитаннями' : 'BEFORE YOU ASK'}</p><h2 className="font-display max-w-2xl text-[clamp(2.5rem,4vw,4.5rem)] font-bold leading-[.96]">{uk ? 'Так, ми це вже чули.' : "Yes, we've heard that one before."}</h2><div className="mt-8"><FAQ faqs={faqs} compact orange /></div></div></section>
      </main>
    </ServicePageLayout>
  );
}
